version: "3.1"

services:
  wordpress:
    image: wordpress
    build:
      context: .
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 8092:80
    networks:
      - local_net
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./html:/var/www/html

networks:
  local_net:
    external: true
